### PR TITLE
Changed deprecated method to new method

### LINKED ISSUE #1090: Deprecated Method Warning when pushing pod with dependency on 2.3 in Xcode
I've pushed pods many times that depended on `2.3` in the past, but after installing Xcode 7, when I try a `pod repo push` for a pod spec with a dependency on `MagicalRecord`, I get the following warnings.
````
    - WARN  |  MagicalRecord/MagicalRecord/Categories/NSManagedObject/NSManagedObject+MagicalRecord.m:246:21: warning: 'MR_deleteInContext:' is deprecated: This method has been deprecated and will be removed in MagicalRecord 4.0. Please use `MR_deleteEntityInContext:` instead. [-Wdeprecated-declarations]
    - NOTE  |  MagicalRecord/MagicalRecord/Categories/NSManagedObject/NSManagedObject+MagicalRecord.h:72:1: note: 'MR_deleteInContext:' has been explicitly marked deprecated here
````

The spec does not validate.

I am able to push the repository using the `--allow-warnings` flag, but this doesn't seem ideal.

I know `2.3.0` was supposed to be the last release until `3.0`, but you might want to consider a patch version `2.3.1` for this. I'd be happy to make a pull request to solve the issue if you will release a `2.3.1`.

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This fixes #1090 and should be pulled for a `2.3.1` release version

### CODE REVIEW

**Comment by tonyarnold** [comment]
Ahhh, sorry @AnthonyMDev — I really need this against `develop`. I wish there was a way to force PRs to a specific branch — we funnel our PRs and work through `develop`, and merge into `master` just for releases (so that `master` always represents the released product).

**Comment by AnthonyMDev** [comment]
One minute. New PR coming

**Comment by tonyarnold** [comment]
I appreciate it — thanks!

**Comment by AnthonyMDev** [comment]
#1092

**Pull request closed without merging**
