### PR TITLE
enable relationship's mappedKeyName.[0-9]

### PR DESCRIPTION
**Pull request by ios122**
enable relationship's mappedKeyName.[0-9]   使关系映射真正支持mappedKeyName.[0-9] ,以支持多重key path映射.

### CODE REVIEW

**Comment by tonyarnold** [comment]
The tests should be fixed in `master` now. 

I'm really not sure what this PR is fixing — could you explain it in some detail please?

Also, would you mind updating the comment you've added in this PR to be in English? 

Thanks!

**Comment by ios122** [comment]
[https://github.com/magicalpanda/MagicalRecord/blob/master/Docs/Importing-Data.md](https://github.com/magicalpanda/MagicalRecord/blob/master/Docs/Importing-Data.md),As the Doc says:"Relationships mappedKeyName.[0-9]	String	Specifies backup keypath names if the key specified by mappedKeyName doesn't exist. Supports the same syntax."; But It Not works Actually!The reason is the original code do nothing when `mappedKeyName` is not Matching! I try to fix this ,it works well in My Project Now.I want you know this!--That's what I want to say! Maybe My code is not the best,u can fix this issue in you ways!

**Comment by ios122** [comment]
"往relationship中导入数据时,要适当适时删除原来的数据:
         如果目标实体没有设置模拟主键"relatedByAttribute",就删除此relationship下所有的目标实体对象,以避免引入不必要的冗余数据.", is meas, when import, some data maybe needs be deleted if they can't be reference any more.It's a Personal Issue ,I think;and I give my idea.

**Comment by ios122** [comment]
I knew u come China, and I think u Chines maybe well!

**Comment by Coeur** [comment]
@ios122 can you change your code comment to English?

**Comment by Coeur** [comment]
A clearer pull request is now available at #1228.

**Pull request closed without merging**
