### PR TITLE
Added autoselect of the default spec based on the CocoalLumberjack availability

### PR DESCRIPTION
**Pull request by anton-matosov**
Fix for #988 as addition to #1101

### CODE REVIEW

**Comment by tonyarnold** [comment]
Does this actually work? Those look like C defines, not Ruby defines — also the podspec is converted to JSON when you submit to trunk. 

Can you point me at the CocoaPods documentation for this feature please :smile:

**Comment by anton-matosov** [comment]
Yes, it does work. It passes lint. I have found this in the history of the MagicalRecord.podspec. I will give you the reference a bit later.

**Comment by anton-matosov** [comment]
No. It doesn't... you are right. I have used changes from https://github.com/rivera-ernesto/MagicalRecord/commit/208b3b407bc5d9105e8e7e60a5f5189955f5e92c but I didn't pay attention that they are content of the pre-compiled header... and with my changes I was simply overriding the default subspec...

**Comment by anton-matosov** [comment]
So it is incorrect change.

**Comment by tonyarnold** [comment]
Thanks for the time you put into this all the same. I appreciate you wanting to improve MR :)

**Comment by anton-matosov** [comment]
you are welcome =)

**Pull request closed without merging**
