### PR TITLE
Little fixes

### PR DESCRIPTION
**Pull request by Antol**

### CODE REVIEW

**Comment by Antol** [comment]
Second commit about this problem 
http://stackoverflow.com/questions/3923826/nsfetchedresultscontroller-with-predicate-ignores-changes-merged-from-different/3927811#3927811

**Comment by tonyarnold** [comment]
Actually, belay that — I read the SO thread and it makes sense. Could I get you to write a couple of quick unit tests to verify the expected behaviour, and that the problem these changes fix stay fixed? Thanks!

**Comment by Antol** [comment]
Oops! I forget about tests

**Comment by tonyarnold** [comment]
That's OK — when you get a chance, tests would be great. Just submit another PR :)

**Pull request merged**
