### PR TITLE
Fix broken MagicalRecordShouldDeletePersistentStoreOnModelMismatchKey

### PR DESCRIPTION
**Pull request by diejmon**
See #803 for more detail, but `MagicalRecordShouldDeletePersistentStoreOnModelMismatchKey` is being ignored for auto migrating SQL stacks.

[Review on Reviewable](https://reviewable.io/reviews/magicalpanda/magicalrecord/804)

### CODE REVIEW

**Comment by tonyarnold** [comment]
While I appreciate the time you've put into this I don't see how we could merge the PR as it stands (and also, merge conflict). 

What is DSMagicalRecord?

**Comment by tonyarnold** [comment]
If you can boil this down to just the changes necessary to fix #803, that would be appreciated!

**Comment by diejmon** [comment]
I'm sorry initial PR was mush smaller. I will send you details about the issue later. Along with new stack, where there is private queue context linked to coordinator. This allows to move access to disk out of main thread.

**Comment by tonyarnold** [comment]
I really appreciate the time you put into this, but without trimming this back to something mergable I can't do much more here. Closing for now, feel free to reopen when you have time.

**Pull request closed without merging**
