### PR TITLE
Module support

### PR DESCRIPTION
**Pull request by tonyarnold**
In order to exist in a Swifty world, we need to get on the module train properly. This means a number of changes to the project structure, and potentially enabling shorthand by default for MagicalRecord 2. 

All work for this should happen in this branch until it's ready to go.

Notable changes:

- Proper dynamic frameworks for iOS and OS X, including proper framework-style imports
- Module support, which means no more importing via the Objective-C bridging header in Swift sources

Breaking changes:

- Shorthand has been removed entirely. We've been planning on doing this for a while, and given that nobody on the team has time to maintain this feature anymore it is time for it to go. I'm open to suggestions about how we can maintain this in a simpler fashion with some level of safety.

### CODE REVIEW

**Comment by kevintuhumury** [comment]
Looking at #936 this seems to be what I need in my Swift project with Cocoapods enabled. @tonyarnold Does this need more work? If not, is it going to be merged anytime soon?

**Comment by tonyarnold** [comment]
@kevintuhumury I honestly don't have an ETA. I am giving @magicalpanda/team-magicalrecord a chance to look over the PR and make comment before merging — unfortunately, it seems everyone is a bit busy right now.

**Comment by kevintuhumury** [comment]
I wanted to test your branch in my project, but I'm getting an error in your `.pch` file. I've tried to include your branch like this:

```
pod "MagicalRecord/Shorthand", git: "https://github.com/magicalpanda/MagicalRecord.git", branch: "module-support"
```

The error I get is `'CoreData+MagicalRecord.h' file not found`. That file is indeed not included when I look into the MagicalRecord pod. I get the same error when I change `MagicalRecord/Shorthand` to just `MagicalRecord`. 

I'm not sure if it's even supposed to work like this.

**Comment by tonyarnold** [comment]
@kevintuhumury sorry for the delay in replying — I was away on business this week. 

Part of moving to a module is providing a decent umbrella header — I figured it was a good time to update:

```objective-c
#import <MagicalRecord/MagicalRecord.h>

// OR!

@import MagicalRecord;
```

Nice and consistent :smile:

**Comment by jonasman** [comment]
yeah this is not working too. Also when compiling the code there are tons of errors in the MR

**Comment by tonyarnold** [comment]
Can you post the errors please?

**Comment by kevintuhumury** [comment]
@tonyarnold Don't worry about the delay, we all have our lives :). I'm not sure if I'm doing it right. To be honest I'm new to iOS development and haven't done anything with Objective-C yet. 

I'd like to use MagicalRecord instead of SugarRecord or any of the other Swift equivalents since this library seems more mature. I've added MagicalRecord like the following in my Podfile:

```
pod "MagicalRecord/Shorthand", git: "https://github.com/magicalpanda/MagicalRecord.git", branch: "module-support"
```

And I have a bridging header file which contains:

```
#import <Foundation/Foundation.h>
#import <MagicalRecord/CoreData+MagicalRecord.h>
```

Now, I'm not sure what you meant with your comment. Should I adjust the `.pch` file in the MagicalRecord pod directory to include what you suggested or should I adjust my bridging header file with:

```
#import <MagicalRecord/MagicalRecord.h>
```

I tried both and in both situations I get errors (which are probably related to my project), but I'm just making sure that I'm doing what you intended us to do.

P.S. I'm sorry for hijacking your pull request like this.

**Comment by tonyarnold** [comment]
@kevintuhumury not a problem — this is why it's a PR, so I can sort through any issues like this. There are big changes in here, and it means I need to write docs (and I haven't properly yet). 

Yes, you should update your pch to look like:

```objective-c
#import <Foundation/Foundation.h>
#import <MagicalRecord/MagicalRecord.h>
```
To be honest, there may be issues with the podspec given the changes I've made. You won't need the shorthand anymore, so you can probably just update your Podfile to:

```ruby
pod "MagicalRecord", git: "https://github.com/magicalpanda/MagicalRecord.git", branch: "module-support"
```

If you could post the errors you're seeing here (or better yet in a gist) that would be a huge help.

**Comment by kevintuhumury** [comment]
@tonyarnold I've created a [gist](https://gist.github.com/kevintuhumury/ef7f207a91a18e770b0f) with the error I currently have.

**Comment by kevintuhumury** [comment]
@tonyarnold I previously posted a gist with the error I had. Shortly after posting it my project compiled by updating the `.pch` file in the MagicalRecord pod directory.

After that I've included a `NSManagedObject` subclass, which is now causing some problems. I'm not completely sure it's related to MagicalRecord or to Core Data in general, so I've created a [question on StackOverflow](http://stackoverflow.com/questions/29134342/swift-linker-error-for-nsmanagedobject-subclass-implementing-a-protocol-with-a-r).

**Comment by jonasman** [comment]
@import MagicalRecord; -> Module magicalRecord not found

**Comment by kevintuhumury** [comment]
I currently have a problem with calling `createEntity` on my model. I completely changed my setup from my previous comment and currently have this model:

```
@objc(Foo)
class Foo: NSManagedObject {
  @NSManaged var bar: String
}
```

Without the `let foo = Foo.createEntity() as Foo` call everything compiles and runs fine. When I do use that function it results in the following error: `'Foo.Type' does not have a member named 'createEntity'`, which seems related to #857.

**Comment by tonyarnold** [comment]
Kevin, does `let foo = Foo.MR_createEntity()` work as expected?

**Comment by kevintuhumury** [comment]
@tonyarnold Yes, it does. I didn't even think to use that, but indeed. The following works fine:

```
let foo = Foo.MR_createEntity()
```

**Comment by tonyarnold** [comment]
Righto, well it sounds like my changes to enable `MR_SHORTHAND` by default aren't working right then. Thanks for confirming.

**Pull request merged**
