### PR TITLE
watchOS updates!

### PR DESCRIPTION
**Pull request by stury**
These are small changes needed to compile MagicalRecord on watchOS!  We
need this for getting our app engine to run on watchOS.

### CODE REVIEW

**Comment by ekimia** [comment]
bump - if we have eyes to get this in it would be extremely useful

**Comment by casademora** [comment]
I'll take a look at this soon. thanks for submitting this...

**Comment by ekimia** [comment]
awesome, if it checks out i can update it with master unless @stury beats me to it

**Comment by stury** [comment]
I’d love it if you would incorporate it into the master!  We’re using a fork of MagicalRecord until this gets into the main release.

Shouldn’t be much to do to get this working on tvOS as well.

Thanks!

Scott Tury

**Comment by casademora** [comment]
Well, I'm trying to get back into everything after lots of craziness...thanks for being patient...

**Comment by jasonscharff** [comment]
Will this be merged soon?

**Comment by stury** [comment]
Interesting, I did not notice the "all checks have failed" on this PR.  I just took a look at the log for the checks, and it looks like it's only failure is for code signing.  Has anyone checked the travis setup to make sure you can code sign the appropriate parts?  

```
Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
```

**Comment by lexin** [comment]
So. Do we have ability to use MagicalRecord with watchOS? Can't find true link.

**Comment by stury** [comment]
I'm not sure why the automated merging of this PR is not working.  It seems to be a configuration issue with the current setup.  

There are a few things that are not available on watchOS.  But unless you're using those specific features, you should be good to go to use MagicalRecord on watchOS - as well as tvOS!

I'm using my updates in multiple projects at the moment on watchOS and tvOS.  You can get my fork of the MagicalRecord code at https://github.com/stury/MagicalRecord .  I'd love for it to be integrated into the main codebase though!

**Comment by lexin** [comment]
Great! Thank you, stury. I successfully installed it from your git.

**Comment by Coeur** [comment]
tvOS doesn't support `NSPersistentStoreUbiquitousContentURLKey`, so testing for `#ifndef TARGET_OS_WATCH` is not enough.

**Comment by Coeur** [comment]
I've done the relevant code change for watchOS compatibility on master (see #1362). Now I just need to add the targets.

**Comment by stury** [comment]
Thank You!

**Comment by Coeur** [comment]
Done in #1363

**Pull request closed without merging**
