### PR TITLE
Docs examples in swift

### PR DESCRIPTION
**Pull request by ssuhanov**
Added swift examples to documentations

### CODE REVIEW

**Comment by perryprog** [comment]
This is kinda a big deal for people who don't know a thing about Obj C.

**Comment by ssuhanov** [comment]
@perryprog thanks, hope this pull-request will be merged. :)

**Comment by ssuhanov** [comment]
@perryprog please, decline my pull request if it not actual now. Or approve it if it is. :) Hope it will helpful for your users. :)

**Comment by perryprog** [comment]
@ssuhanov I'm not a admin of this: I just wanted to use this for a project but I had trouble figuring out thee documentation.

TL;DR: I'm a random guy who had nothing to do with this

**Comment by ssuhanov** [comment]
@perryprog oh, sorry, man. I saw that you approved these changes on Dec 29, 2016. And I thought that you can merge this PR to the repo. :)

**Comment by perryprog** [comment]
@ssuhanov I wish 🙂

**Pull request closed without merging**
