### PR TITLE
Added MagicalRecordShorthandMethodAliases.h to private headers so it …

### PR DESCRIPTION
**Pull request by anton-matosov**
…is not getting included into umbrealla header and enabled by default in swift

### CODE REVIEW

**Comment by tonyarnold** [comment]
Looks fine to me, however are the shorthand methods still usable for CocoaPods users when this header is marked private? (manually linking in the header)

**Comment by anton-matosov** [comment]
It should. Let me double check.

**Comment by anton-matosov** [comment]
It didn't work with frameworks, so I had to use excludes instead of private headers and create a 'Shorthands' subspec to be able to still include them.
Although this approach looks better as it works natively with frameworks and can be used with CocoaLumberjack subspec.
Usage examples:

No shorthands:
```
  pod 'MagicalRecord'
```

With shorthands:
```
  pod 'MagicalRecord'
  pod 'MagicalRecord/Shorthands'
```

With CocoaLumberjack and shorthands:
```
  pod 'MagicalRecord/CocoaLumberjack'
  pod 'MagicalRecord/Shorthands'
```

**Comment by anton-matosov** [comment]
I can't reproduce crash of the test in dev environment.

**Comment by tonyarnold** [comment]
I've merged this in as 2cc8027b307b46a623cf4c5e76fc15e3b3fb9890 with the subspec name `MagicalRecord/ShorthandMethodAliases`. Thanks for the PR!

**Pull request closed without merging**
