### PR TITLE
Update MagicalRecord.podspec

### PR DESCRIPTION
**Pull request by melbic**
Fixing Issue: https://github.com/magicalpanda/MagicalRecord/issues/988

I didn't test what happens if CocoaLumberjack wasn't used in a project...

### CODE REVIEW

**Comment by tonyarnold** [comment]
> I didn't test what happens if CocoaLumberjack wasn't used in a project...

Any chance that you could? I'm not going to have time to test this for a week or so.

**Comment by melbic** [comment]
I don't know if I'll find time for it this week, but I'll try.

**Comment by melbic** [comment]
Sometimes you have to take the time. But it actually doesn't work. It fails with:
```
ld: framework not found CocoaLumberJack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I didn't find a way to add the framework as optional.

**Comment by tonyarnold** [comment]
What I'd say we have to do is add a "MagicalRecord+CocoaLumberjack" subspec that users can chose to use over the standard "MagicalRecord" one. That subspec could link in CL.

**Comment by melbic** [comment]
I added a Subspec, so the version with CocoaLumberjack as dependency can be installed with:
   `
    pod "MagicalRecord/CocoaLumberjack"
    `

**Comment by scottrhoyt** [comment]
Can we get this pulled? I think there's a few of us waiting on this one. Thanks!

**Comment by bpoplauschi** [comment]
This update should be propagated to the CocoaPods/Specs repo so we all get it.

**Comment by lolgear** [comment]
done?

**Comment by bpoplauschi** [comment]
Guys, you need to make this update to Cocoapods/Specs. We cannot make it. Apparently, only Saul Mora and Tony Arnold can.

**Pull request merged**
