### PR TITLE
Enable much stricter warnings, and turn on warnings as errors

### PR DESCRIPTION
**Pull request by tonyarnold**
So this might be a bit contentious, but I'd like to tidy up MR 3 for release at the same time as modernising as much as possible. 

Not sure you're going to agree with all of this, @casademora, but it has helped me to write better code (and I'm hoping it will help as I walk through and fix a few things).

### CODE REVIEW

**Comment by casademora** [comment]
Wha? You removed the oxford semi-colons? 😓

**Comment by casademora** [comment]
Over all I'm ok with the changes. It looks like they make the code more consistent and well named, so I'm all for it. Huge thanks to @tonyarnold for this! 🎊🎉

**Comment by tonyarnold** [comment]
I know you were fond of the semicolons, but it was time dude.

**Comment by tonyarnold** [comment]
@casademora if you're happy for me to merge this in, let's do it and then merge this into `master`. It's time to focus development on 3.0.

**Comment by magicalpandatest** [comment]
I cling to the traditions of my ancestors…

**Comment by tonyarnold** [comment]
I BBQ'ed my ancestors in a purifying :fire:, then ate them with some chunky steak fries

**Pull request merged**
